[DEFAULT]
; dataset_path = /home/chinenye/Documents/fall2024/SigstoreTrends/dataset2/dataset
; error_dataset_path = /home/chinenye/Documents/fall2024/SigstoreTrends/dataset2/error_dataset
; all_dataset_path = /media/chinenye/allrekordataset/dataset
small_dataset_path = /home/chinenye/Documents/fall2024/SigstoreTrends/dataset_small/dataset

all_dataset_path = /mnt/chinenye/rekordataset/dataset/
malicious_packages_path = /home/chinenye/Documents/fall2024/malicious-packages/osv/malicious
unknown_Obj_path = issues_folder/unknown_obj.txt
none_type_path = issues_folder/none_type_file.txt
wrong_ascii_filepath = issues_folder/wrong_ascii.txt

limit = 1e9


